# 实验说明

## 作业说明

### 目标：

训练一个玩数独的神经网络，并得到较高的准确率

### 背景：

数独是一种经典的逻辑游戏，玩家需要根据9×9盘面上的已知数字，推理出所有剩余空格的数字，并满足每一行、每一列、每一个粗线宫（3x3）内的数字均含数字1～9，不重复。本教程展示如何训练一个用于产生数独游戏解的神经网络模型，并评估其准确率和计算时间。该模型得到9x9每个位置上填入数字1～9的概率分布（共有9x9x9个概率）。

**训练过程**：将模型输出的概率分布与 ground truth 得到交叉熵 loss，并反向传播更新梯度。

**推理过程**：我们**逐个地**填入数字，过程为先选中某个位置，再选择1～9的一个数字进行填入。
循环执行以下操作，直到全部填充完毕：

1. 将 1x9x9 的数独游戏输入模型，输出 81x9 的概率分布

2. 每个位置如果需要填入，一定会选择数字1～9中概率最大的填入。即：

$num_{x,y} = argmax(P_{x,y,1},P_{x,y,2},\cdots,P_{x,y,9})$

3. 每次需要选择一个空位置进行填入，我们选择所有空位置 $(x,y)$ 中 $P_{x,y}$ 最大的填入。

$P_{x,y} = max(P_{x,y,1},P_{x,y,2},\cdots,P_{x,y,9}) $

$chosenP = argmax(P_{x,y})$

### 任务：

#### Q1： 训练模型

运行baseline，训练和评估模型，并记录平均损失。你可以使用自己的数独游戏，输出结果，以判断模型是否可以得到合理的结果。

由于数独可能存在多个合理解，因此只比较和 ground truth 的差别，并非是好的评估方式。请修改模型评估的代码，判断解是否合理，并计算模型得到合理解的概率。**请于q1.diff提交你的代码。**

#### Q2： 尝试数据增广

数独游戏可以尝试多种数据增广：左右翻转，上下翻转，旋转后性质不变；将1～9数字重新排列（shuffle）后，性质也不变。使用更小的样本（例如仅使用1000个训练数据），并修改代码，尝试使用更多的增广方式进行训练，得到Q1中的准确率尽可能高的模型。**请于q2.diff提交你的代码。**

#### Q3： 训练一个量化神经网络

从 baseline 模型中，提取量化神经网络。可以参考本文以了解量化的工作原理：[DoReFa-Net: Training Low Bitwidth Convolutional Neural Networks with Low Bitwidth Gradients](https://arxiv.org/abs/1606.06160)。

建议分别将量化权重和特征的位数设置为2和1，你也可以使用其他配置。你可以使用 ground truth 进行训练，也可以采用知识蒸馏的方式，尝试获得更好的效果。详见：[知识蒸馏教程](https://studio.brainpp.com/project/4719)。

完成以上任务，得到Q1中的准确率尽可能高的量化模型。 **请于q3.diff提交你的代码。**

## 数据集

来源：[1 million Sudoku games](https://www.kaggle.com/bryanpark/sudoku)，该数独数据集包含100万对9x9网格下的数独游戏以及解，存储于`./dataset/dataset-2115/sudoku.csv`。

## 文件存储
实验中生成的文件可以存储于 workspace 目录中。 查看工作区文件，该目录下的变更将会持久保存。 您的所有项目将共享一个存储空间，请及时清理不必要的文件，避免加载过慢。

## 实验步骤

1.导入库

In [4]:
import numpy as np
import megengine as mge
import megengine.module as M
import megengine.functional as F
import megengine.data.transform as T
import pandas as pd
import copy
from tqdm import tqdm
from typing import Tuple
from megengine import tensor
from sklearn.model_selection import train_test_split
from megengine.data import DataLoader, RandomSampler
from megengine.data.dataset import Dataset
from megengine.tensor import Parameter
from megengine.optimizer import Adam
from megengine.autodiff import GradManager

2.设计模型结构，并实例化模型

In [5]:
class Net(M.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv0 = M.Conv2d(1, 64, kernel_size=3, stride=1, padding=1)
        self.relu0 = M.ReLU()
        self.bn0 = M.BatchNorm2d(64)
        self.conv1 = M.Conv2d(64, 64, kernel_size=3, stride=1, padding=1)
        self.relu1 = M.ReLU()
        self.bn1 = M.BatchNorm2d(64)
        self.conv2 = M.Conv2d(64, 64, kernel_size=3, stride=1, padding=1)
        self.relu2 = M.ReLU()
        self.bn2 = M.BatchNorm2d(64)
        self.conv3 = M.Conv2d(64, 64, kernel_size=3, stride=1, padding=1)
        self.relu3 = M.ReLU()
        self.bn3 = M.BatchNorm2d(64)
        self.conv4 = M.Conv2d(64, 128, kernel_size=1, stride=1, padding=0)
        self.relu4 = M.ReLU()
        self.fc = M.Linear(10368, 81*9)

    def forward(self, x):
        x = self.conv0(x)
        x = self.relu0(x)
        x = self.bn0(x)
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.bn1(x)
        x = self.conv2(x)
        x = self.relu2(x)
        x = self.bn2(x)
        x = self.conv3(x)
        x = self.relu3(x)
        x = self.bn3(x)
        x = self.conv4(x)
        x = self.relu4(x)
        x = F.flatten(x, 1)
        x = self.fc(x)
        x = F.reshape(x, (-1, 81, 9))
        return x

model = Net()
print("model initialized")

model initialized


3.准备训练数据，设置优化器

In [6]:
padding_size = 3

def get_data(file): 
    data = pd.read_csv(file)
    feat_raw = data['quizzes']
    label_raw = data['solutions']
    feat = []
    label = []

#     for i in feat_raw:
#         x = np.array([int(j) for j in i]).reshape((1,9,9))
#         feat.append(x)
#     feat = np.array(feat)
#     feat = feat/9
#     feat -= .5 
#     for i in label_raw:
#         x = np.array([int(j) for j in i]).reshape((1,81)) - 1
#         label.append(x)
#     label = np.array(label)
    
    s = set()
    t = 0
    for i in range(len(feat_raw)):
        x = feat_raw[i]
        y = label_raw[i]
        z = np.array([int(j) for j in y]).reshape((1, 81)) - 1
        if x not in s:
            s.add(x)
            a = np.array([int(j) for j in x]).reshape((1, 9, 9))
            feat.append(a)
            b = [z for j in range(padding_size)]
            label.append(b)
            t = 1
        else:
            label[-1][t] = z
            t += 1
    feat = np.array(feat)
    feat = feat/9
    feat -= .5
    label = np.array(label)
    
    del(feat_raw)
    del(label_raw)    

    x_train, x_test, y_train, y_test = train_test_split(feat, label, test_size=0.2, random_state=42)
    
    return x_train, x_test, y_train, y_test

x_train, x_test, y_train, y_test = get_data('data/sudoku_extended.csv')

class TrainDataset(Dataset):
    def __init__(self,x_train,y_train):
        super().__init__()
        self.data_x = x_train
        self.data_y = y_train
    def __getitem__(self, index:int) -> Tuple:
        return self.data_x[index], self.data_y[index]
    def __len__(self) -> int:
        return len(self.data_x)

train_dataset = TrainDataset(x_train, y_train)
train_sampler = RandomSampler(dataset = train_dataset, batch_size=32)
train_dataloader = DataLoader(dataset = train_dataset, sampler=train_sampler)

opt = Adam(model.parameters(), lr = 1e-3)
print("Data Loaded")

Data Loaded


4.训练模型

In [8]:
print("start training")

epochs = 2
for epoch in range(epochs):
    iter = 0
    with tqdm(total=train_dataloader.__len__() / 100, desc="epoch {}:training process".format(epoch)) as tq:
        for i, (feat, label) in enumerate(train_dataloader):
            gm = GradManager().attach(model.parameters())
            with gm:
                logits = model(tensor(feat))
                label = label.reshape(32, padding_size, 81)
                loss = tensor(0)
                for j in range(32):
                    l = tensor(F.ones(padding_size))
                    for k in range(padding_size):
                        l[k] = F.loss.cross_entropy(logits[j], label[j][k], axis=1)
                    loss += l.min()
                
                iter += 1
                if iter % 100 == 0:
                    tq.set_postfix({"loss": "{0:1.5f}".format(loss.numpy().item()),})
                    tq.update(1)
                    
                gm.backward(loss)
            opt.step()
            opt.clear_grad()

mge.save(model, "1.mge")
print("saved")

epoch 0:training process:   0%|          | 0/250.0 [00:00<?, ?it/s]

training start


epoch 0:training process: 100%|██████████| 250/250.0 [1:03:21<00:00, 15.21s/it, loss=10.92054]
epoch 1:training process: 100%|██████████| 250/250.0 [1:03:19<00:00, 15.20s/it, loss=10.82663]

saved


5.模型评估

你需要修改这部分的代码，以完成作业Q1。

In [16]:
model = Net()
model = mge.load("1.mge")
model.eval()

eval_dataset = TrainDataset(x_test, y_test)
eval_sampler = RandomSampler(dataset = eval_dataset, batch_size=32)
eval_dataloader = DataLoader(dataset = eval_dataset, sampler=eval_sampler)

print("start evaluating")
average_loss = 0
average_acc = 0.
iter = 0
with tqdm(total=eval_dataloader.__len__() / 100, desc="evaluating process") as tq:
    for i, (feat, label) in enumerate(eval_dataloader):
            logits = model(tensor(feat))
            label = label.reshape(32, padding_size, 81)
            loss = tensor(0)
            for j in range(32):
                l = tensor(F.ones(padding_size))
                r = []
                for k in range(padding_size):
                    l[k] = F.loss.cross_entropy(logits[j], label[j][k], axis=1)
                    a = F.softmax(logits[j])
                    a = a.reshape(81, 9)
                    pred = F.argmax(a, axis=1).reshape((81))
                    correct = F.sum(F.equal(pred, tensor(label[j][k])))
                    r.append(correct / 81)
                loss += l.min()
                average_acc += max(r)/32
            
            iter += 1
            if iter % 100 == 0:
                tq.set_postfix({"loss": "{0:1.5f}".format(loss.numpy().item()/32),})
                tq.update(1)
            average_loss += loss.numpy().item()/32

print(average_loss / eval_dataloader.__len__())
print(average_acc / eval_dataloader.__len__())

evaluating process:   0%|          | 0/62.5 [00:00<?, ?it/s]

start evaluating


evaluating process:  99%|█████████▉| 62/62.5 [10:35<00:05, 10.24s/it, loss=0.31998]

0.33382902927398683
Tensor(0.8442119, device=xpux:0)


6.输入一个你自己的数独游戏，并查看模型的输出结果。

In [17]:
model = Net()
model = mge.load("1.mge")
model.eval()

def norm(x):
    return (x/9)-.5

def denorm(x):
    return (x+.5)*9

def inference_sudoku(sample):
    feat = copy.copy(sample)
    
    while(1):
        out = F.softmax(model(tensor(feat.reshape((1, 1, 9, 9)))), axis= 2)
        out = out.reshape(81, 9)

        pred = F.argmax(out, axis=1).reshape((9, 9))+1 
        prob = np.around(F.max(out, axis=1).reshape((9, 9)), 2) 
        feat = denorm(feat).reshape((9, 9))
        mask = ( feat == 0 )
        if mask.sum() == 0:
            break
            
        prob_new = prob * mask 
        ind = F.argmax(prob_new) 
        x, y = (ind // 9), (ind % 9)
        
        val = pred[x][y].numpy()
        feat[x][y] = int(val)
        feat = norm(feat)
    
    return feat

def solve_sudoku(game):
    
    game = game.replace('\n', '')
    game = game.replace(' ', '')
    game = np.array([int(j) for j in game]).reshape((9,9,1))
    game = norm(game)
    game = inference_sudoku(game)
    return game

game = '''
          0 8 0 0 3 2 0 0 1
          7 0 3 0 8 0 0 0 2
          5 0 0 0 0 7 0 3 0
          0 5 0 0 0 1 9 7 0
          6 0 0 7 0 9 0 0 8
          0 4 7 2 0 0 0 5 0
          0 2 0 6 0 0 0 0 9
          8 0 0 0 9 0 3 0 5
          3 0 0 8 2 0 0 1 0
      '''

game = solve_sudoku(game)

print('solved puzzle:\n')
print(game.astype("uint8"))

solved puzzle:

[[4 8 9 5 3 2 7 6 1]
 [7 1 3 4 8 6 5 9 2]
 [5 6 2 9 1 7 8 3 4]
 [2 5 8 3 4 1 9 7 6]
 [6 3 1 7 5 9 2 4 8]
 [9 4 7 2 6 8 1 5 3]
 [1 2 5 6 7 3 4 8 9]
 [8 7 6 1 9 4 3 2 5]
 [3 9 4 8 2 5 6 1 7]]


## 结果展示

展示为baseline效果。

![sudoku.png](https://data.megengine.org.cn/megstudio/images/sudoku.png)